name: CI for Dev Unit Tests

on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov coverage pytest-mock
      
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: np-devops-team1/DevOps_Main
        
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        repository: np-devops-team1/DevOps_Dev_UnitTest
        path: test_cases
        token: ${{ secrets.DEV_REMOTE }}
        
    - name: Get Branch Name
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Check branch name
      run: |

        tag="$(cut -d'/' -f1 <<< steps.vars.outputs.short_ref)"
        name="$(cut -d'/' -f2 <<< steps.vars.outputs.short_ref)"

        echo "TAG=$tag" >> $GITHUB_ENV
        echo "NAME=$name" >> $GITHUB_ENV
        
        echo $${{tag}}
        echo $${{name}}
        echo $${{env.TAG}}
        echo $${{env.NAME}}

    - name: Analysing code with flake8
      run: |
        flake8
        
    - name: Checkout Test Script
      if: ${{ env.TAG == 'ci' }}
      uses: actions/checkout@v2
      with:
        repository: np-devops-team1/DevOps_Dev_UnitTest
        path: test_cases
        token: ${{ secrets.DEV_REMOTE }}
        
    - name: Build coverage file
      if: ${{ env.TAG == 'feat' }}
      run: |
        mv ./test_cases/test_${{env.NAME}} ./
        pytest --cache-clear --cov=app test/ > pytest-coverage.txt
        
    - name: Comment coverage
      if: ${{ env.TAG == 'feat' }}
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt