name: CI for Dev Unit Tests

on: [push, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Libraries
      run: |
        pip install flake8 pytest pytest-cov coverage pytest-mock
      
    - name: Checkout Own Repo
      uses: actions/checkout@v2
      with: 
        repository: np-devops-team1/DevOps_Main
        
    - name: Checkout Test Script
      uses: actions/checkout@v2
      with:
        repository: np-devops-team1/DevOps_Dev_UnitTest
        path: test_cases
        token: ${{ secrets.DEV_REMOTE }}

    - name: Check branch name
      run: |

        tag_branch="$(cut -d'/' -f1 <<< ${GITHUB_REF#refs/heads/})"
        name_branch="$(cut -d'/' -f2 <<< ${GITHUB_REF#refs/heads/})"
        
        echo "${GITHUB_REF}"
        echo "NAME_BRANCH=$(echo $name_branch)" >> $GITHUB_ENV
        echo "TAG_BRANCH=$(echo $tag_branch)" >> $GITHUB_ENV

        echo "$tag_branch"
        echo "$name_branch"
        echo ${{TAG_BRANCH}}
        echo ${{NAME_BRANCH}}

    - name: Analysing code with flake8
      run: |
        flake8
        
    - name: Checkout Test Script
      if: ${{TAG_BRANCH == 'feat' }}
      uses: actions/checkout@v2
      with:
        repository: np-devops-team1/DevOps_Dev_UnitTest
        path: test_cases
        token: ${{ secrets.DEV_REMOTE }}
        
    - name: Build coverage file
      if: ${{TAG_BRANCH == 'feat' }}
      run: |
        mv ./test_cases/test_${{NAME}} ./
        pytest --cache-clear --cov=app test/ > pytest-coverage.txt
        
    - name: Comment coverage
      if: ${{TAG_BRANCH == 'feat' }}
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt