name: Release

on:
  release:
    types: [published]

jobs:
  release-actions:
    name: Post-Release Actions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Notify Stakeholders on Release
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            New Release From Tag: ${{ github.ref }} Now Available! @dongkiat
